#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
VERSION="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$ROOT_DIR/MarkdownPreviewApp/Info.plist")"
TAG="v$VERSION"
RELEASE_DIR="$ROOT_DIR/release"
PKG_PATH="$RELEASE_DIR/MarkdownPreview-$VERSION.pkg"
CHECKSUM_PATH="$PKG_PATH.sha256"
NOTES_PATH="$RELEASE_DIR/MarkdownPreview-$VERSION-release-notes.md"
MODE="prepare"

usage() {
  cat <<USAGE
Usage: ./scripts/release.sh [--prepare|--draft|--publish]

  --prepare   Build release assets locally. This is the default.
  --draft     Build assets and create a draft GitHub release.
  --publish   Build assets and create a public GitHub release.
USAGE
}

if [[ $# -gt 1 ]]; then
  usage
  exit 2
fi

case "${1:---prepare}" in
  --prepare)
    MODE="prepare"
    ;;
  --draft)
    MODE="draft"
    ;;
  --publish)
    MODE="publish"
    ;;
  -h|--help)
    usage
    exit 0
    ;;
  *)
    usage
    exit 2
    ;;
esac

cd "$ROOT_DIR"

"$ROOT_DIR/scripts/package.sh"

/usr/bin/shasum -a 256 "$PKG_PATH" > "$CHECKSUM_PATH"

cat > "$NOTES_PATH" <<NOTES
# Markdown Preview $VERSION

Native macOS Quick Look previews for Markdown files.

## Install

1. Download \`MarkdownPreview-$VERSION.pkg\` and \`MarkdownPreview-$VERSION.pkg.sha256\`.
2. Verify the package checksum.
3. Open the package. If macOS blocks the unsigned package, remove the quarantine flag first.
4. In Finder, select a Markdown file and press Space.

## Verify

\`\`\`sh
shasum -a 256 -c MarkdownPreview-$VERSION.pkg.sha256
\`\`\`

## Unsigned Package Warning

This package is unsigned unless the release explicitly says it is signed and notarized. macOS may show a warning that Apple cannot check it for malicious software.

After verifying the checksum, install the unsigned package with:

\`\`\`sh
xattr -dr com.apple.quarantine MarkdownPreview-$VERSION.pkg
open MarkdownPreview-$VERSION.pkg
\`\`\`

## Notes

- Installs to \`~/Applications/Markdown Preview.app\`.
- Registers the bundled Quick Look extension.
- Sets Markdown Preview as the Viewer handler for Markdown files without changing your editor association.
- The package generated by this repository is unsigned unless you sign and notarize it separately.
NOTES

echo "Created $PKG_PATH"
echo "Created $CHECKSUM_PATH"
echo "Created $NOTES_PATH"

if [[ "$MODE" == "prepare" ]]; then
  exit 0
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "gh is required to create a GitHub release." >&2
  exit 1
fi

gh auth status >/dev/null

if gh release view "$TAG" >/dev/null 2>&1; then
  echo "Release $TAG already exists." >&2
  exit 1
fi

release_args=(
  release create "$TAG"
  "$PKG_PATH"
  "$CHECKSUM_PATH"
  --title "Markdown Preview $VERSION"
  --notes-file "$NOTES_PATH"
)

if [[ "$MODE" == "draft" ]]; then
  release_args+=(--draft)
fi

gh "${release_args[@]}"
echo "Created GitHub release $TAG."
